CREATE TABLE IF NOT EXISTS payments(
  id SERIAL PRIMARY KEY,
  reference VARCHAR(40) NOT NULL,
  amount_cents INT NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'LKR',
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
